/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package screens;

import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import models.Patient;

/**
 *
 * @author tapas
 */
public class FormPanel extends javax.swing.JPanel {

    File patientImage;
    SimpleDateFormat formatter = new SimpleDateFormat("dd-MMMM-yyyy");
    JSplitPane splitPane;
    JPanel bottomPanel;
    public FormPanel(JPanel bottomPanel, JSplitPane splitPane) {
        this.bottomPanel = bottomPanel;
        this.splitPane = splitPane;
        initComponents();
        buttonGroup.add(radioMale);
        buttonGroup.add(radioFemale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        cmbPatientType = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        lblFileName = new javax.swing.JLabel();
        txtDob = new com.toedter.calendar.JDateChooser();
        lblAge = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(701, 430));

        jLabel1.setText("First Name");
        jLabel1.setPreferredSize(new java.awt.Dimension(20, 10));

        txtFname.setPreferredSize(new java.awt.Dimension(20, 15));

        txtLname.setPreferredSize(new java.awt.Dimension(20, 15));

        jLabel2.setText("Last Name");
        jLabel2.setPreferredSize(new java.awt.Dimension(20, 10));

        jLabel3.setText("Date Of Birth");
        jLabel3.setPreferredSize(new java.awt.Dimension(20, 10));

        txtEmail.setPreferredSize(new java.awt.Dimension(20, 15));

        jLabel4.setText("Email ID");
        jLabel4.setPreferredSize(new java.awt.Dimension(20, 10));

        jLabel5.setText("Message");
        jLabel5.setPreferredSize(new java.awt.Dimension(20, 10));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(20, 10));

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        txtMessage.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtMessage);

        jLabel6.setText("Patient Type");
        jLabel6.setPreferredSize(new java.awt.Dimension(20, 10));

        cmbPatientType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Serious", "Critical", "Emergency", "Regular" }));
        cmbPatientType.setPreferredSize(new java.awt.Dimension(20, 10));

        jLabel7.setText("Patient Image");
        jLabel7.setPreferredSize(new java.awt.Dimension(20, 10));

        btnBrowse.setText("Browse");
        btnBrowse.setPreferredSize(new java.awt.Dimension(20, 10));
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        lblFileName.setPreferredSize(new java.awt.Dimension(20, 10));

        txtDob.setPreferredSize(new java.awt.Dimension(20, 21));
        txtDob.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDobPropertyChange(evt);
            }
        });

        lblAge.setPreferredSize(new java.awt.Dimension(20, 10));

        lblImage.setPreferredSize(new java.awt.Dimension(20, 10));

        btnSubmit.setText("Submit");
        btnSubmit.setPreferredSize(new java.awt.Dimension(20, 10));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel8.setText("Gender");
        jLabel8.setPreferredSize(new java.awt.Dimension(20, 10));

        radioMale.setSelected(true);
        radioMale.setText("Male");

        radioFemale.setText("Female");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtLname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(97, 97, 97))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(radioMale)
                                    .addGap(18, 18, 18)
                                    .addComponent(radioFemale)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPatientType, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPatientType, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(lblFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioMale)
                            .addComponent(radioFemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Image",
            "jpg", "jpeg", "png"));
    if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
        if (validateFileType(fileChooser.getSelectedFile())) {
            patientImage = fileChooser.getSelectedFile();
            lblFileName.setText(patientImage.getName());
            lblImage.setIcon(new ImageIcon(new ImageIcon(patientImage.getAbsolutePath())
                .getImage().getScaledInstance(100, 100,
                    Image.SCALE_SMOOTH)));
        } else {
            showDialog(null, "Please select Image only!");
        }
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void txtDobPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDobPropertyChange
        // TODO add your handling code here:
        if(txtDob.getDate() != null){
            lblAge.setText("Age: "+(LocalDate.now().getYear() -
                Integer.parseInt(formatter.format(txtDob.getDate()).split("-")[2]))+" years");
        }
    }//GEN-LAST:event_txtDobPropertyChange

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        Patient patient = new Patient(
            txtFname.getText().trim(),
            txtLname.getText().trim(),
            txtDob.getDate() == null ? null : formatter.format(txtDob.getDate()),
            txtEmail.getText().trim(),
            txtMessage.getText().trim(),
            cmbPatientType.getSelectedItem().toString(),
            radioMale.isSelected() ? "MALE" : "FEMALE",
            patientImage);
        String error = validate(patient);
        if(error.isBlank()){
            
            javax.swing.JLabel titleLabel = (javax.swing.JLabel)splitPane.getTopComponent();
            DisplayPanel display = new DisplayPanel(patient, bottomPanel, titleLabel);
            bottomPanel.add(display);
            CardLayout cl = (CardLayout) bottomPanel.getLayout();
            titleLabel.setText("Patient Details");
            cl.next(bottomPanel);
        }else{
            showDialog(null, error);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

                                             

    String validate(Patient patient) {
        String emailIDRegex = "[^@ \\t\\r\\n]+@[^@ \\t\\r\\n]+\\.[^@ \\t\\r\\n]+";

        Pattern emailPattern = Pattern.compile(emailIDRegex);

        String errorMessage = "";

        /**
         ******* NOT Using If-Else ladder because I want to check for every
         * variable to be empty or not and frame the error message accordingly
         * *******
         */
        if (patient.getfName() == null || patient.getfName().isBlank()) {
            errorMessage += "Please enter your First Name!";
        }
        if (patient.getlName() == null || patient.getlName().isBlank()) {
            errorMessage += (!errorMessage.isBlank() ? "\n" : "")
                    + "Please enter your Last Name!";

        }
        if (patient.getDob() == null || patient.getDob().isBlank()) {
            errorMessage += (!errorMessage.isBlank() ? "\n" : "")
                    + "Please enter your Date of Birth!";

        }else {
            int age = LocalDate.now().getYear() - Integer.parseInt(patient.getDob().split("-")[2]);
            if ((age < 5 || age > 100)) {
                errorMessage += (!errorMessage.isBlank() ? "\n" : "")
                        + "Age should be between 5 to 100 Years!";

            } 
        }
        
        if (patient.getEmail()== null || patient.getEmail().isBlank()) {
            errorMessage += (!errorMessage.isBlank() ? "\n" : "")
                    + "Please enter your Email ID!";

        }else if (!emailPattern.matcher(patient.getEmail()).matches()) {
                errorMessage += (!errorMessage.isBlank() ? "\n" : "")
                        + "Please enter correct Email ID!";
        }
        
        if (patient.getPatientType()== null || patient.getPatientType().toUpperCase().equals("SELECT")) {
            errorMessage += (!errorMessage.isBlank() ? "\n" : "")
                    + "Please select Patient Type!";

        }
        if (patient.getImage() == null) {
            errorMessage += (!errorMessage.isBlank() ? "\n" : "")
                    + "Please select your Profile Picture!";

        } 
        return errorMessage;
    }
    boolean validateFileType(File f) {
        String ext = f.getName().split("\\.")[1].toLowerCase();
        return ("png".equals(ext)
                || "jpg".equals(ext)
                || "jpeg".equals(ext));
    }

    void showDialog(Patient patient, String errorMessage) {
        if (patient == null) {
            JOptionPane.showMessageDialog(this, errorMessage,
                    "Error...!",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            Image image = new ImageIcon(patient.getImage().getAbsolutePath())
                    .getImage().getScaledInstance(100, 100,
                            Image.SCALE_SMOOTH);
            JOptionPane.showMessageDialog(this,
                    patient.toString(),
                    "Details Saved successfully...!",
                    JOptionPane.OK_OPTION,
                    new ImageIcon(image));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox<String> cmbPatientType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFileName;
    private javax.swing.JLabel lblImage;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private com.toedter.calendar.JDateChooser txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextArea txtMessage;
    // End of variables declaration//GEN-END:variables
}
