/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import java.awt.Image;
import java.io.File;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import models.UserProfileModel;

/**
 *
 * @author tapaswi
 */
public class ProfileScreen extends javax.swing.JFrame {

    UserProfileModel userProfile = null;
    String firstName = null;
    String lastName = null;
    double age = -1;
    String mobileNumber = null;
    String emailID = null;
    File profilePicture = null;

    /**
     * Creates new form UserProfile
     */
    public ProfileScreen() {
        initComponents();
        init();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void init() {
        this.setLocationRelativeTo(null);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlPersonalDetails = new javax.swing.JPanel();
        lblSectionTitle1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblFName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JTextField();
        lblMobNumber = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        pnlProfilePicture = new javax.swing.JPanel();
        lblSectionTitle2 = new javax.swing.JLabel();
        btnUploadPicture = new javax.swing.JButton();
        lblImageName = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(135, 176, 242));
        lblTitle.setText("Profile Details");

        pnlPersonalDetails.setBackground(new java.awt.Color(28, 28, 30));

        lblSectionTitle1.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblSectionTitle1.setForeground(new java.awt.Color(135, 176, 242));
        lblSectionTitle1.setText("Personal Details");

        lblFName.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        lblFName.setForeground(new java.awt.Color(135, 176, 242));
        lblFName.setText("First Name");

        lblLName.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        lblLName.setForeground(new java.awt.Color(135, 176, 242));
        lblLName.setText("Last Name");

        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgeKeyTyped(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        lblAge.setForeground(new java.awt.Color(135, 176, 242));
        lblAge.setText("Age");

        lblMobNumber.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        lblMobNumber.setForeground(new java.awt.Color(135, 176, 242));
        lblMobNumber.setText("Mobile Number");

        txtEmail.setPreferredSize(new java.awt.Dimension(183, 35));

        lblEmail.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(135, 176, 242));
        lblEmail.setText("Email ID");

        javax.swing.GroupLayout pnlPersonalDetailsLayout = new javax.swing.GroupLayout(pnlPersonalDetails);
        pnlPersonalDetails.setLayout(pnlPersonalDetailsLayout);
        pnlPersonalDetailsLayout.setHorizontalGroup(
            pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSectionTitle1))
                    .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail)
                                    .addComponent(lblAge)
                                    .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblFName)
                                        .addComponent(lblLName)))
                                .addGap(38, 38, 38)
                                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                                .addComponent(lblMobNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pnlPersonalDetailsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAge, txtEmail, txtFirstName, txtLastName, txtMobileNumber});

        pnlPersonalDetailsLayout.setVerticalGroup(
            pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSectionTitle1)
                .addGap(18, 18, 18)
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFName))
                .addGap(12, 12, 12)
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge))
                .addGap(12, 12, 12)
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMobNumber)
                    .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pnlPersonalDetailsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAge, txtEmail, txtFirstName, txtLastName, txtMobileNumber});

        pnlProfilePicture.setBackground(new java.awt.Color(28, 28, 30));

        lblSectionTitle2.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblSectionTitle2.setForeground(new java.awt.Color(135, 176, 242));
        lblSectionTitle2.setText("Profile Picture");

        btnUploadPicture.setText("Select Picture");
        btnUploadPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPictureActionPerformed(evt);
            }
        });

        lblImageName.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        lblImageName.setForeground(new java.awt.Color(135, 176, 242));

        javax.swing.GroupLayout pnlProfilePictureLayout = new javax.swing.GroupLayout(pnlProfilePicture);
        pnlProfilePicture.setLayout(pnlProfilePictureLayout);
        pnlProfilePictureLayout.setHorizontalGroup(
            pnlProfilePictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfilePictureLayout.createSequentialGroup()
                .addGroup(pnlProfilePictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProfilePictureLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblSectionTitle2))
                    .addGroup(pnlProfilePictureLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnUploadPicture)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImageName, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        pnlProfilePictureLayout.setVerticalGroup(
            pnlProfilePictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfilePictureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSectionTitle2)
                .addGap(18, 18, 18)
                .addGroup(pnlProfilePictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImageName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUploadPicture))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSubmit.setBackground(new java.awt.Color(135, 176, 242));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(pnlPersonalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlProfilePicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitle)
                        .addGap(298, 298, 298))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(320, 320, 320))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlProfilePicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPersonalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        firstName = txtFirstName.getText().trim();
        lastName = txtLastName.getText().trim();
        try {
            age = Double.parseDouble(txtAge.getText().trim());
        } catch (NumberFormatException e) {
            age = -1;
        }
        mobileNumber = txtMobileNumber.getText().trim();
        emailID = txtEmail.getText().trim();
        String errorMessage = performValidations();

        if (errorMessage.isBlank()) {
            userProfile = new UserProfileModel(
                    firstName,
                    lastName,
                    age,
                    mobileNumber,
                    emailID,
                    profilePicture
            );
            showDialog(userProfile, errorMessage);
        } else {
            showDialog(null, errorMessage);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnUploadPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPictureActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Image",
                "jpg", "jpeg", "png"));
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            if(validateFileType(fileChooser.getSelectedFile())){
                profilePicture = fileChooser.getSelectedFile();
                lblImageName.setText(profilePicture.getName());
            }else{
                showDialog(null, "Please select Image only!");
            }
        }
    }//GEN-LAST:event_btnUploadPictureActionPerformed

    boolean validateFileType(File f){
        String ext = f.getName().split("\\.")[1].toLowerCase();
        return ("png".equals(ext) 
                || "jpg".equals(ext) 
                || "jpeg".equals(ext));
    }
    
    private void txtAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyTyped
        // TODO add your handling code here:
        try{
            if(!txtAge.getText().trim().isBlank())
                Double.parseDouble(txtAge.getText().trim());
        }catch(NumberFormatException e){
            txtAge.setText("");
            showDialog(null, "Only numbers are allowed for Age!");
        }
    }//GEN-LAST:event_txtAgeKeyTyped

    String performValidations() {
        String mobileNumberRegex = "^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$";
        String emailIDRegex = "[^@ \\t\\r\\n]+@[^@ \\t\\r\\n]+\\.[^@ \\t\\r\\n]+";

        Pattern mobileNumberPattern = Pattern.compile(mobileNumberRegex);
        Pattern emailPattern = Pattern.compile(emailIDRegex);

        String errorMessage = "";

        /**
         ******* NOT Using If-Else ladder because I want to check for every
         * variable to be empty or not and frame the error message accordingly
         * *******
         */
        if (firstName == null || firstName.isBlank()) {
            errorMessage += "Please enter your First Name!";
        }
        if (lastName == null || lastName.isBlank()) {
            errorMessage += (!errorMessage.isBlank() ? "\n" : "")
                    + "Please enter your Last Name!";

        }
        if (age == -1) {
            errorMessage += (!errorMessage.isBlank() ? "\n" : "")
                    + "Please enter your Age!";

        }
        if (mobileNumber == null || mobileNumber.isBlank()) {
            errorMessage += (!errorMessage.isBlank() ? "\n" : "")
                    + "Please enter your Mobile Number!";

        }
        if (emailID == null || emailID.isBlank()) {
            errorMessage += (!errorMessage.isBlank() ? "\n" : "")
                    + "Please enter your Email ID!";

        }
        if (profilePicture == null) {
            errorMessage += (!errorMessage.isBlank() ? "\n" : "")
                    + "Please select your Profile Picture!";

        } else {
            if (age != -1 && (age < 5 && age > 100)) {
                errorMessage += (!errorMessage.isBlank() ? "\n" : "")
                        + "Age should be between 5 to 100 Years!";

            } else if (!mobileNumberPattern.matcher(mobileNumber).matches()) {
                errorMessage += (!errorMessage.isBlank() ? "\n" : "")
                        + "Please enter correct Mobile Number!";

            } else if (!emailPattern.matcher(emailID).matches()) {
                errorMessage += (!errorMessage.isBlank() ? "\n" : "")
                        + "Please enter correct Email ID!";
            }
        }
        return errorMessage;
    }

    void showDialog(UserProfileModel userProfile, String errorMessage) {
        if (userProfile == null) {
            JOptionPane.showMessageDialog(this, errorMessage,
                    "Error...!",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            Image image = new ImageIcon(userProfile.getProfilePicture().getAbsolutePath())
                            .getImage().getScaledInstance(100, 100,
                                    Image.SCALE_SMOOTH);
            JOptionPane.showMessageDialog(this,
                    userProfile.toString(),
                    "Details Saved successfully...!",
                    JOptionPane.OK_OPTION,
                    new ImageIcon(image));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUploadPicture;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblImageName;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblMobNumber;
    private javax.swing.JLabel lblSectionTitle1;
    private javax.swing.JLabel lblSectionTitle2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnlPersonalDetails;
    private javax.swing.JPanel pnlProfilePicture;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobileNumber;
    // End of variables declaration//GEN-END:variables
}
